### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by EmirVelazquez** [EmirVelazquez/fccPortfolio#1]
Need to complete navbar with links for page navigation and logo

**Comment by doana1** [comment]
![image](https://user-images.githubusercontent.com/4966663/82148086-3132a700-9820-11ea-84e8-04f54a8508eb.png)

**Comment by EmirVelazquez** [comment]
Navbar created, links for navigation to different sections done. Also created a modern simplistic logo for navbar using figma.
